---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    app.kubernetes.io/part-of: maas-demo-architectures
---
apiVersion: v1
kind: Namespace
metadata:
  name: models-as-a-service
  labels:
    app.kubernetes.io/part-of: maas-demo-architectures
